services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=${MONGODB_DATABASE:syncplaylist}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:secret}'
      - 'MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:root}'
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: