services:
  mongodb:
    image: 'mongo:8.0.13'
    container_name: database
    environment:
      - MONGO_INITDB_DATABASE=syncplaylist
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_ROOT_USERNAME=root
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: