spring:
  application:
    name: sync-playlist
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: secret
      database: syncplaylist

server:
  port: 9000

app:
  jwt:
    secret: mySecretKey1234567890123456789012345678901234567890
    expiration: 86400000
    issuer: sync-playlist
    algorithm: HS256